[package]
name = "traffic"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flo_draw = "0.3"
flo_canvas = "0.3.0"
#rand = "0.8.3"
